# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/proto/execution.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/proto/execution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eservices/proto/execution.proto\x12\x08services\"b\n\x0cTradeRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x01\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"_\n\rTradeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12\x14\n\x0c\x66illed_price\x18\x04 \x01(\x01\"\x12\n\x10PortfolioRequest\"\xc4\x01\n\x11PortfolioResponse\x12=\n\tpositions\x18\x01 \x03(\x0b\x32*.services.PortfolioResponse.PositionsEntry\x12\x14\n\x0c\x63\x61sh_balance\x18\x02 \x01(\x01\x12\x14\n\x0ctotal_equity\x18\x03 \x01(\x01\x1a\x44\n\x0ePositionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.services.Position:\x02\x38\x01\"Z\n\x08Position\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\x15\n\raverage_price\x18\x03 \x01(\x01\x12\x15\n\rcurrent_value\x18\x04 \x01(\x01\x32\x9c\x01\n\x10\x45xecutionService\x12?\n\x0c\x45xecuteTrade\x12\x16.services.TradeRequest\x1a\x17.services.TradeResponse\x12G\n\x0cGetPortfolio\x12\x1a.services.PortfolioRequest\x1a\x1b.services.PortfolioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.proto.execution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PORTFOLIORESPONSE_POSITIONSENTRY']._loaded_options = None
  _globals['_PORTFOLIORESPONSE_POSITIONSENTRY']._serialized_options = b'8\001'
  _globals['_TRADEREQUEST']._serialized_start=44
  _globals['_TRADEREQUEST']._serialized_end=142
  _globals['_TRADERESPONSE']._serialized_start=144
  _globals['_TRADERESPONSE']._serialized_end=239
  _globals['_PORTFOLIOREQUEST']._serialized_start=241
  _globals['_PORTFOLIOREQUEST']._serialized_end=259
  _globals['_PORTFOLIORESPONSE']._serialized_start=262
  _globals['_PORTFOLIORESPONSE']._serialized_end=458
  _globals['_PORTFOLIORESPONSE_POSITIONSENTRY']._serialized_start=390
  _globals['_PORTFOLIORESPONSE_POSITIONSENTRY']._serialized_end=458
  _globals['_POSITION']._serialized_start=460
  _globals['_POSITION']._serialized_end=550
  _globals['_EXECUTIONSERVICE']._serialized_start=553
  _globals['_EXECUTIONSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
