# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/proto/signals.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/proto/signals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cservices/proto/signals.proto\x12\x07signals\".\n\rSignalRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05\x61s_of\x18\x02 \x01(\t\"\x9b\x01\n\x0cSignedSignal\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x15\n\rfeatures_hash\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\t\x12\x15\n\rpublic_key_id\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x14\n\x0cpayload_json\x18\x07 \x01(\t2K\n\rSignalService\x12:\n\tGetSignal\x12\x16.signals.SignalRequest\x1a\x15.signals.SignedSignalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.proto.signals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREQUEST']._serialized_start=41
  _globals['_SIGNALREQUEST']._serialized_end=87
  _globals['_SIGNEDSIGNAL']._serialized_start=90
  _globals['_SIGNEDSIGNAL']._serialized_end=245
  _globals['_SIGNALSERVICE']._serialized_start=247
  _globals['_SIGNALSERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
