"""initial_schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-03-23

Creates:
  - assets table (asset registry)
  - market_data table (TimescaleDB hypertable on 'time')
  - Composite index (asset_id, time DESC) for time-range queries

NOTE: This file is generated by `alembic revision --autogenerate -m 'initial_schema'`
and then amended manually to add TimescaleDB-specific DDL (hypertable + index).
The autogenerate step creates the CREATE TABLE blocks; the three op.execute() calls
below are manual additions — Alembic does not know about TimescaleDB DDL.

Phase 2 — TimescaleDB Schema & Repository Layer
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ---------------------------------------------------------------------------
# Alembic revision identifiers
# ---------------------------------------------------------------------------
revision = "0001_initial_schema"
down_revision = None          # first migration in the chain
branch_labels = None
depends_on = None


# ---------------------------------------------------------------------------
# Upgrade — apply changes
# ---------------------------------------------------------------------------

def upgrade() -> None:
    # ------------------------------------------------------------------
    # assets — canonical asset registry
    # ------------------------------------------------------------------
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint(
            "symbol", "asset_class", "source", name="uq_asset_identity"
        ),
    )

    # ------------------------------------------------------------------
    # market_data — OHLCV time-series
    # Composite PK (time, asset_id) is required by TimescaleDB; a single-
    # column PK on 'time' alone is rejected for partitioned hypertables.
    # ------------------------------------------------------------------
    op.create_table(
        "market_data",
        sa.Column(
            "time",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_market_data_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("time", "asset_id", name=op.f("pk_market_data")),
    )

    # ------------------------------------------------------------------
    # TimescaleDB DDL — must come AFTER the standard CREATE TABLE
    # ------------------------------------------------------------------

    # 1. Convert market_data into a TimescaleDB hypertable partitioned by
    #    time, with a secondary space partition on asset_id (4 partitions).
    #    This is equivalent to the guide's step 3 SQL.
    op.execute(
        """
        SELECT create_hypertable(
            'market_data',
            'time',
            partitioning_column => 'asset_id',
            number_partitions   => 4,
            if_not_exists       => TRUE
        )
        """
    )

    # 2. Composite index: (asset_id, time DESC) — optimised for per-asset
    #    time-range queries used by fetch_range().  TimescaleDB propagates
    #    this index across all chunks automatically.
    op.execute(
        "CREATE INDEX ix_market_data_asset_time ON market_data (asset_id, time DESC)"
    )

    # 3. Optional: enable TimescaleDB compression (comment out if not needed)
    # op.execute(
    #     """
    #     ALTER TABLE market_data SET (
    #         timescaledb.compress,
    #         timescaledb.compress_segmentby = 'asset_id'
    #     )
    #     """
    # )
    # op.execute(
    #     "SELECT add_compression_policy('market_data', INTERVAL '7 days')"
    # )


# ---------------------------------------------------------------------------
# Downgrade — undo changes
# ---------------------------------------------------------------------------

def downgrade() -> None:
    # Drop in reverse order of creation.
    # TimescaleDB drops all chunks automatically when the hypertable is dropped.
    op.drop_table("market_data")
    op.drop_table("assets")
