/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List registered assets
         * @description Registered assets, alphabetically by symbol.
         *
         *     This is what a UI populates a symbol picker from. `count` is the number
         *     returned in this page, not the total matching the filter.
         */
        get: operations["list_assets_api_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One asset, with its stored data coverage
         * @description Asset metadata plus how much history is stored for it.
         *
         *     Coverage matters to a consumer before it requests a date range: five
         *     registered crypto tickers have zero bars because every legacy row for them
         *     was an empty padding bar.
         */
        get: operations["get_asset_api_v1_assets__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ohlcv/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily OHLCV bars for one symbol over a date range
         * @description Return daily bars for `symbol` between `start` and `end`, ascending by time.
         *
         *     404 means the symbol is not registered. A known symbol with no bars in the
         *     requested window returns 200 with an empty `bars` list — an empty result is
         *     not an error.
         */
        get: operations["get_ohlcv_api_v1_ohlcv__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available strategies
         * @description Every registered strategy and its parameter schema.
         *
         *     A UI can build its entire strategy picker — including per-strategy
         *     parameter controls with defaults and bounds — from this response alone.
         */
        get: operations["list_strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One strategy's schema */
        get: operations["get_strategy_api_v1_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a strategy backtest over stored history
         * @description Fetch history, run the strategy, return equity curve + KPIs + trades.
         *
         *     The backtest itself is CPU-bound and runs in a threadpool so a long run does
         *     not block the event loop and stall every other request.
         */
        post: operations["run_backtest_api_v1_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unsigned strategy signals for a symbol
         * @description Run a strategy over the range and return its per-bar signal.
         *
         *     `params` is JSON-encoded because this is a GET — the endpoint stays a
         *     cacheable read rather than becoming a POST just to carry a body. The
         *     response echoes the parameters actually used, so a caller can always tell
         *     what produced the signals it is looking at.
         */
        get: operations["get_signals_api_v1_signals__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness probe.
         *
         *     Confirms the process is running. Container orchestrators (Docker Compose,
         *     Kubernetes) use this to decide whether to restart the container.
         */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe.
         *
         *     Verifies downstream dependencies (TimescaleDB) are reachable before the
         *     container is marked healthy. Returns 503 if the DB is unavailable so the
         *     orchestrator withholds traffic until the pool is ready.
         */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetDetail
         * @description Adds coverage, which requires an aggregate over market_data.
         */
        AssetDetail: {
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Source */
            source: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Bar Count
             * @description Number of stored bars
             */
            bar_count: number;
            /**
             * First Bar
             * @description Earliest bar timestamp
             */
            first_bar?: string | null;
            /**
             * Last Bar
             * @description Latest bar timestamp
             */
            last_bar?: string | null;
        };
        /** AssetListResponse */
        AssetListResponse: {
            /** Count */
            count: number;
            /** Assets */
            assets: components["schemas"]["AssetSummary"][];
        };
        /** AssetSummary */
        AssetSummary: {
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Source */
            source: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** BacktestRequest */
        BacktestRequest: {
            /**
             * Symbol
             * @description Ticker as stored, e.g. 'AAPL'
             */
            symbol: string;
            /**
             * Strategy Id
             * @description Registry id, e.g. 'ma_crossover'
             */
            strategy_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Params
             * @description Strategy parameters. Omitted parameters use registry defaults.
             */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Initial Capital
             * @default 100000
             */
            initial_capital: number;
            /**
             * Transaction Cost
             * @description Per-trade cost as a fraction, e.g. 0.001 = 10bps
             * @default 0.001
             */
            transaction_cost: number;
            /**
             * Seed
             * @description Seed for simulated slippage. Defaults to 42 so the same request always returns the same result — without it, identical backtests differ run to run and saved results cannot be reproduced. Pass a different int to sample another draw, or null for unseeded (non-reproducible) behaviour.
             * @default 42
             */
            seed: number | null;
            /**
             * Include Equity Curve
             * @description Set false for a metrics-only response
             * @default true
             */
            include_equity_curve: boolean;
            /**
             * Include Trades
             * @default true
             */
            include_trades: boolean;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Symbol */
            symbol: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Bars
             * @description Bars fed to the strategy
             */
            bars: number;
            /**
             * Params
             * @description Parameters actually used, defaults filled in
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Seed
             * @description Slippage seed used for this run
             */
            seed?: number | null;
            /**
             * Metrics
             * @description KPIs from PerformanceAnalyzer
             */
            metrics: {
                [key: string]: unknown;
            };
            /**
             * Caveat
             * @description Non-null when the strategy is known to be unsound
             */
            caveat?: string | null;
            /** Equity Curve */
            equity_curve?: components["schemas"]["EquityPoint"][];
            /** Trades */
            trades?: {
                [key: string]: unknown;
            }[];
        };
        /** EquityPoint */
        EquityPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Total */
            total: number;
            /** Cash */
            cash: number;
            /** Holdings */
            holdings: number;
            /** Position */
            position: number;
            /** Signal */
            signal: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OHLCVBar
         * @description A single OHLCV bar. Price fields are nullable — the legacy data has gaps.
         */
        OHLCVBar: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Open */
            open?: number | null;
            /** High */
            high?: number | null;
            /** Low */
            low?: number | null;
            /** Close */
            close?: number | null;
            /** Volume */
            volume?: number | null;
        };
        /** OHLCVResponse */
        OHLCVResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Asset Class
             * @description 'equity' | 'crypto' | 'option' | 'future'
             */
            asset_class: string;
            /**
             * Source
             * @description Data provider, e.g. 'yfinance'
             */
            source: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Count
             * @description Number of bars returned
             */
            count: number;
            /** Bars */
            bars: components["schemas"]["OHLCVBar"][];
        };
        /** ParamSchema */
        ParamSchema: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "int" | "float" | "str";
            /** Default */
            default: unknown;
            /** Label */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Minimum */
            minimum?: number | null;
            /** Maximum */
            maximum?: number | null;
        };
        /** SignalPoint */
        SignalPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Signal
             * @description +1 long, -1 short/exit, 0 flat. Null where the strategy is still warming up.
             */
            signal: number | null;
            /**
             * Close
             * @description Close price at that bar
             */
            close?: number | null;
        };
        /** SignalsResponse */
        SignalsResponse: {
            /** Symbol */
            symbol: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Count */
            count: number;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Signed
             * @description Always false. These are unsigned strategy signals; signed signals are served by the gRPC/GraphQL layer, not this API.
             * @default false
             */
            signed: boolean;
            /** Caveat */
            caveat?: string | null;
            /** Signals */
            signals: components["schemas"]["SignalPoint"][];
        };
        /** StrategyListResponse */
        StrategyListResponse: {
            /** Count */
            count: number;
            /** Strategies */
            strategies: components["schemas"]["StrategySchema"][];
        };
        /** StrategySchema */
        StrategySchema: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /**
             * Input Contract
             * @description 'single' takes one symbol's OHLCV frame; 'multi' takes a wide multi-symbol frame and cannot be backtested on a single symbol.
             * @enum {string}
             */
            input_contract: "single" | "multi";
            /** Params */
            params: components["schemas"]["ParamSchema"][];
            /**
             * Caveat
             * @description Set when the strategy is known to be unsound — surface it to the user.
             */
            caveat?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assets_api_v1_assets_get: {
        parameters: {
            query?: {
                /** @description Filter by 'equity' or 'crypto' */
                asset_class?: string | null;
                /** @description Case-insensitive symbol substring match */
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker as stored, e.g. 'AAPL' or 'BTC-USD' */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            /** @description Symbol is not in the asset registry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ohlcv_api_v1_ohlcv__symbol__get: {
        parameters: {
            query: {
                /** @description Inclusive range start (ISO 8601) */
                start: string;
                /** @description Inclusive range end (ISO 8601) */
                end: string;
                /** @description Optional disambiguator. Omit it — symbols are unique in the current registry, and the API deliberately does not infer asset class from the ticker. */
                asset_class?: string | null;
                /** @description Filter by data provider */
                source?: string | null;
            };
            header?: never;
            path: {
                /** @description Ticker as stored, e.g. 'AAPL' or 'BTC-USD' */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OHLCVResponse"];
                };
            };
            /** @description Symbol is not in the asset registry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_v1_strategies_get: {
        parameters: {
            query?: {
                /** @description Filter by input contract. Pass 'single' for symbol-by-symbol backtests. */
                input_contract?: ("single" | "multi") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_v1_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registry id, e.g. 'ma_crossover' */
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySchema"];
                };
            };
            /** @description No such strategy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_api_v1_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Unknown symbol or strategy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters, bad date range, or no data */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_signals_api_v1_signals__symbol__get: {
        parameters: {
            query: {
                /** @description Registry id, e.g. 'ma_crossover' */
                strategy_id: string;
                /** @description Inclusive range start (ISO 8601) */
                start: string;
                /** @description Inclusive range end (ISO 8601) */
                end: string;
                /** @description JSON object of strategy parameters, e.g. {"short_window": 10, "long_window": 30}. Omitted parameters use registry defaults. Unknown names are rejected with 422 rather than ignored. */
                params?: string | null;
                /** @description Include the Close price alongside each signal */
                include_close?: boolean;
            };
            header?: never;
            path: {
                /** @description Ticker as stored, e.g. 'AAPL' */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsResponse"];
                };
            };
            /** @description Unknown symbol or strategy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters, bad date range, or no data */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
