/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List registered assets
         * @description Registered assets, alphabetically by symbol.
         *
         *     This is what a UI populates a symbol picker from. `count` is the number
         *     returned in this page, not the total matching the filter.
         */
        get: operations["list_assets_api_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One asset, with its stored data coverage
         * @description Asset metadata plus how much history is stored for it.
         *
         *     Coverage matters to a consumer before it requests a date range: five
         *     registered crypto tickers have zero bars because every legacy row for them
         *     was an empty padding bar.
         */
        get: operations["get_asset_api_v1_assets__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ohlcv/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily OHLCV bars for one symbol over a date range
         * @description Return daily bars for `symbol` between `start` and `end`, ascending by time.
         *
         *     404 means the symbol is not registered. A known symbol with no bars in the
         *     requested window returns 200 with an empty `bars` list — an empty result is
         *     not an error.
         */
        get: operations["get_ohlcv_api_v1_ohlcv__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available strategies
         * @description Every registered strategy and its parameter schema.
         *
         *     A UI can build its entire strategy picker — including per-strategy
         *     parameter controls with defaults and bounds — from this response alone.
         */
        get: operations["list_strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One strategy's schema */
        get: operations["get_strategy_api_v1_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screeners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available screeners
         * @description Every registered screener and its parameter schema.
         *
         *     Same contract as /api/v1/strategies: a UI builds its whole screener panel,
         *     including per-screener controls with defaults and bounds, from this alone.
         */
        get: operations["list_screeners_api_v1_screeners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screeners/{screener_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One screener's schema */
        get: operations["get_screener_api_v1_screeners__screener_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screeners/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Filter a universe through one or more screeners
         * @description Fetch history for each symbol, then apply the screeners in order.
         *
         *     Symbols with no bars in the range are excluded before screening and counted
         *     in `with_data`, so an empty result distinguishes "nothing passed the filter"
         *     from "nothing had data".
         */
        post: operations["run_screen_api_v1_screeners_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available tests
         * @description Every registered test with its arity, input kind and parameter schema — a
         *     UI builds its whole panel from this, including how many symbols to ask for.
         */
        get: operations["list_tests_api_v1_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/{test_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One test's schema */
        get: operations["get_test_api_v1_statistics__test_id__get"];
        put?: never;
        /**
         * Run a statistical test over stored history
         * @description Fetch each symbol's closes, align them, convert to returns if the test
         *     needs returns, then run it.
         *
         *     Symbol ORDER is preserved and significant: OLS treats the first symbol as
         *     the asset and the second as the benchmark, so sorting them would silently
         *     invert alpha and beta.
         */
        post: operations["run_test_api_v1_statistics__test_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a strategy backtest over stored history
         * @description Fetch history, run the strategy, return equity curve + KPIs + trades.
         *
         *     The backtest itself is CPU-bound and runs in a threadpool so a long run does
         *     not block the event loop and stall every other request.
         */
        post: operations["run_backtest_api_v1_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest a multi-asset strategy across a portfolio */
        post: operations["run_portfolio_backtest_api_v1_backtest_portfolio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimize/strategy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grid-search a strategy's parameters on one symbol */
        post: operations["optimize_strategy_api_v1_optimize_strategy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimize/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Monte Carlo search for optimal portfolio weights */
        post: operations["optimize_portfolio_api_v1_optimize_portfolio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unsigned strategy signals for a symbol
         * @description Run a strategy over the range and return its per-bar signal.
         *
         *     `params` is JSON-encoded because this is a GET — the endpoint stays a
         *     cacheable read rather than becoming a POST just to carry a body. The
         *     response echoes the parameters actually used, so a caller can always tell
         *     what produced the signals it is looking at.
         */
        get: operations["get_signals_api_v1_signals__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness probe.
         *
         *     Confirms the process is running. Container orchestrators (Docker Compose,
         *     Kubernetes) use this to decide whether to restart the container.
         */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe.
         *
         *     Verifies downstream dependencies (TimescaleDB) are reachable before the
         *     container is marked healthy. Returns 503 if the DB is unavailable so the
         *     orchestrator withholds traffic until the pool is ready.
         */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllocationPoint */
        AllocationPoint: {
            /** Annualized Return */
            annualized_return: number;
            /** Annualized Volatility */
            annualized_volatility: number;
            /** Sharpe Ratio */
            sharpe_ratio: number;
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /**
         * AssetDetail
         * @description Adds coverage, which requires an aggregate over market_data.
         */
        AssetDetail: {
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Source */
            source: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Bar Count
             * @description Number of stored bars
             */
            bar_count: number;
            /**
             * First Bar
             * @description Earliest bar timestamp
             */
            first_bar?: string | null;
            /**
             * Last Bar
             * @description Latest bar timestamp
             */
            last_bar?: string | null;
        };
        /** AssetListResponse */
        AssetListResponse: {
            /** Count */
            count: number;
            /** Assets */
            assets: components["schemas"]["AssetSummary"][];
        };
        /** AssetSummary */
        AssetSummary: {
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Source */
            source: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** BacktestRequest */
        BacktestRequest: {
            /**
             * Symbol
             * @description Ticker as stored, e.g. 'AAPL'
             */
            symbol: string;
            /**
             * Strategy Id
             * @description Registry id, e.g. 'ma_crossover'
             */
            strategy_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Params
             * @description Strategy parameters. Omitted parameters use registry defaults.
             */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Initial Capital
             * @default 100000
             */
            initial_capital: number;
            /**
             * Transaction Cost
             * @description Per-trade cost as a fraction, e.g. 0.001 = 10bps
             * @default 0.001
             */
            transaction_cost: number;
            /**
             * Seed
             * @description Seed for simulated slippage. Defaults to 42 so the same request always returns the same result — without it, identical backtests differ run to run and saved results cannot be reproduced. Pass a different int to sample another draw, or null for unseeded (non-reproducible) behaviour.
             * @default 42
             */
            seed: number | null;
            /**
             * Include Equity Curve
             * @description Set false for a metrics-only response
             * @default true
             */
            include_equity_curve: boolean;
            /**
             * Include Trades
             * @default true
             */
            include_trades: boolean;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Symbol */
            symbol: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Bars
             * @description Bars fed to the strategy
             */
            bars: number;
            /**
             * Params
             * @description Parameters actually used, defaults filled in
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Initial Capital
             * @description Starting capital for this run. Echoed because a client needs it to draw a break-even line on the equity curve — it is NOT part of `params`, which carries strategy parameters only.
             */
            initial_capital: number;
            /**
             * Seed
             * @description Slippage seed used for this run
             */
            seed?: number | null;
            /**
             * Metrics
             * @description KPIs from PerformanceAnalyzer
             */
            metrics: {
                [key: string]: unknown;
            };
            /**
             * Caveat
             * @description Non-null when the strategy is known to be unsound
             */
            caveat?: string | null;
            /** Equity Curve */
            equity_curve?: components["schemas"]["EquityPoint"][];
            /** Trades */
            trades?: {
                [key: string]: unknown;
            }[];
        };
        /** EquityPoint */
        EquityPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Total */
            total: number;
            /** Cash */
            cash: number;
            /** Holdings */
            holdings: number;
            /** Position */
            position: number;
            /** Signal */
            signal: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OHLCVBar
         * @description A single OHLCV bar. Price fields are nullable — the legacy data has gaps.
         */
        OHLCVBar: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Open */
            open?: number | null;
            /** High */
            high?: number | null;
            /** Low */
            low?: number | null;
            /** Close */
            close?: number | null;
            /** Volume */
            volume?: number | null;
        };
        /** OHLCVResponse */
        OHLCVResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Asset Class
             * @description 'equity' | 'crypto' | 'option' | 'future'
             */
            asset_class: string;
            /**
             * Source
             * @description Data provider, e.g. 'yfinance'
             */
            source: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Count
             * @description Number of bars returned
             */
            count: number;
            /** Bars */
            bars: components["schemas"]["OHLCVBar"][];
        };
        /** ParamSchema */
        ParamSchema: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "int" | "float" | "str";
            /** Default */
            default: unknown;
            /** Label */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Minimum */
            minimum?: number | null;
            /** Maximum */
            maximum?: number | null;
        };
        /** PortfolioBacktestRequest */
        PortfolioBacktestRequest: {
            /**
             * Symbols
             * @description Constituents, two or more
             */
            symbols: string[];
            /**
             * Strategy Id
             * @description Registry id — must be a multi-asset strategy
             */
            strategy_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Weights
             * @description Target weight per symbol. Omitted means equal-weight. Must cover every requested symbol when supplied — a partial mapping would silently zero-weight the rest.
             */
            weights?: {
                [key: string]: number;
            } | null;
            /**
             * Initial Capital
             * @default 100000
             */
            initial_capital: number;
            /**
             * Seed
             * @description Seed for simulated slippage, so the same request returns the same result. Pass null for unseeded, non-reproducible behaviour.
             * @default 42
             */
            seed: number | null;
            /**
             * Enable Vol Targeting
             * @default false
             */
            enable_vol_targeting: boolean;
            /**
             * Target Volatility
             * @default 0.15
             */
            target_volatility: number;
            /**
             * Include Risk
             * @description Compute VaR/CVaR on the resulting returns
             * @default true
             */
            include_risk: boolean;
            /**
             * Include Equity Curve
             * @default true
             */
            include_equity_curve: boolean;
        };
        /** PortfolioBacktestResponse */
        PortfolioBacktestResponse: {
            /** Symbols */
            symbols: string[];
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Bars */
            bars: number;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Weights
             * @description Weights actually used
             */
            weights: {
                [key: string]: number;
            };
            /** Initial Capital */
            initial_capital: number;
            /** Seed */
            seed: number | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /**
             * Risk Metrics
             * @description VaR/CVaR etc., empty when not requested
             */
            risk_metrics?: {
                [key: string]: unknown;
            };
            /** Caveat */
            caveat?: string | null;
            /** Equity Curve */
            equity_curve?: components["schemas"]["PortfolioEquityPoint"][];
        };
        /** PortfolioEquityPoint */
        PortfolioEquityPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Total */
            total: number;
        };
        /** PortfolioOptimizeRequest */
        PortfolioOptimizeRequest: {
            /**
             * Symbols
             * @description Two or more assets to allocate across
             */
            symbols: string[];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Num Portfolios
             * @default 5000
             */
            num_portfolios: number;
            /**
             * Risk Free Rate
             * @default 0.02
             */
            risk_free_rate: number;
            /**
             * Seed
             * @description Seed for weight sampling. Monte Carlo weights were drawn from the global numpy RNG, so the same request returned different optimal allocations each time.
             * @default 42
             */
            seed: number | null;
            /**
             * Include Frontier
             * @description Return every sampled portfolio for a frontier scatter. Off by default: 5,000 rows each carrying a weights mapping is a large response, and the allocation alone is what most callers want.
             * @default false
             */
            include_frontier: boolean;
            /**
             * Frontier Points
             * @description Cap on returned frontier points; sampled evenly.
             * @default 1000
             */
            frontier_points: number;
        };
        /** PortfolioOptimizeResponse */
        PortfolioOptimizeResponse: {
            /** Symbols */
            symbols: string[];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Bars */
            bars: number;
            /** Num Portfolios */
            num_portfolios: number;
            /** Risk Free Rate */
            risk_free_rate: number;
            /** Seed */
            seed: number | null;
            max_sharpe: components["schemas"]["AllocationPoint"];
            min_volatility: components["schemas"]["AllocationPoint"];
            /** Frontier */
            frontier?: components["schemas"]["AllocationPoint"][];
        };
        /**
         * RangeSpec
         * @description An inclusive numeric sweep. `{"min": 10, "max": 30, "step": 5}`.
         */
        RangeSpec: {
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Step
             * @default 1
             */
            step: number;
        };
        /** ScreenRequest */
        ScreenRequest: {
            /**
             * Symbols
             * @description Universe to filter
             */
            symbols: string[];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Screeners
             * @description Applied in order, each narrowing the output of the last — the same composition ScreenerPipeline performs.
             */
            screeners: components["schemas"]["ScreenerStep"][];
        };
        /** ScreenResponse */
        ScreenResponse: {
            /** Requested */
            requested: number;
            /**
             * With Data
             * @description Symbols that had bars in the range. A symbol with no data cannot be screened and is reported here rather than silently failing the filter — five registered crypto tickers hold zero bars.
             */
            with_data: number;
            /** Passed */
            passed: string[];
            /**
             * Steps
             * @description Per-step counts, so a screen returning nothing shows where it emptied.
             */
            steps: components["schemas"]["ScreenerStepResult"][];
        };
        /** ScreenerListResponse */
        ScreenerListResponse: {
            /** Count */
            count: number;
            /** Screeners */
            screeners: components["schemas"]["ScreenerSchema"][];
        };
        /** ScreenerSchema */
        ScreenerSchema: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Params */
            params: components["schemas"]["ParamSchema"][];
            /** Caveat */
            caveat?: string | null;
        };
        /** ScreenerStep */
        ScreenerStep: {
            /**
             * Screener Id
             * @description Registry id, e.g. 'momentum'
             */
            screener_id: string;
            /**
             * Params
             * @description Omitted parameters use registry defaults.
             */
            params?: {
                [key: string]: unknown;
            };
        };
        /** ScreenerStepResult */
        ScreenerStepResult: {
            /** Screener Id */
            screener_id: string;
            /** Display Name */
            display_name: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Passed
             * @description Symbols surviving this step
             */
            passed: number;
        };
        /** SignalPoint */
        SignalPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Signal
             * @description +1 long, -1 short/exit, 0 flat. Null where the strategy is still warming up.
             */
            signal: number | null;
            /**
             * Close
             * @description Close price at that bar
             */
            close?: number | null;
        };
        /** SignalsResponse */
        SignalsResponse: {
            /** Symbol */
            symbol: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Count */
            count: number;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Signed
             * @description Always false. These are unsigned strategy signals; signed signals are served by the gRPC/GraphQL layer, not this API.
             * @default false
             */
            signed: boolean;
            /** Caveat */
            caveat?: string | null;
            /** Signals */
            signals: components["schemas"]["SignalPoint"][];
        };
        /** SkippedCombination */
        SkippedCombination: {
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
        };
        /** StatisticsRequest */
        StatisticsRequest: {
            /** Symbols */
            symbols: string[];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** StatisticsResponse */
        StatisticsResponse: {
            /** Test Id */
            test_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Symbols
             * @description Symbols actually used, in order
             */
            symbols: string[];
            /**
             * Input Kind
             * @enum {string}
             */
            input_kind: "price" | "returns";
            /**
             * Observations
             * @description Rows fed to the test after alignment
             */
            observations: number;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** StrategyListResponse */
        StrategyListResponse: {
            /** Count */
            count: number;
            /** Strategies */
            strategies: components["schemas"]["StrategySchema"][];
        };
        /** StrategyOptimizeRequest */
        StrategyOptimizeRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Strategy Id
             * @description Registry id — must be single-asset
             */
            strategy_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Grid
             * @description Parameter axes to sweep. Each value is either a list of values or an inclusive range: {"short_window": {"min": 10, "max": 30, "step": 5}, "long_window": [40, 50, 60]}
             */
            grid: {
                [key: string]: unknown[] | components["schemas"]["RangeSpec"];
            };
            /**
             * Params
             * @description Fixed values for parameters not being swept.
             */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Metric
             * @description Metric to rank by. One of: Annualized Return, Annualized Volatility, Calmar Ratio, Final Value, Max Drawdown, Max Drawdown Duration (Days), Sharpe Ratio, Sortino Ratio, Total Return. Note that the risk metrics have a degenerate optimum: the least volatile parameter set is usually one that never trades (zero volatility, zero return). Rank by a risk-ADJUSTED metric such as Sharpe or Calmar unless you specifically want that.
             * @default Sharpe Ratio
             */
            metric: string;
            /**
             * Initial Capital
             * @default 100000
             */
            initial_capital: number;
            /**
             * Transaction Cost
             * @default 0.001
             */
            transaction_cost: number;
            /**
             * Seed
             * @description Slippage seed applied identically to every combination, so the ranking reflects the parameters rather than the draw. Pass null for unseeded, non-reproducible behaviour.
             * @default 42
             */
            seed: number | null;
            /**
             * Top N
             * @default 25
             */
            top_n: number;
        };
        /** StrategyOptimizeResponse */
        StrategyOptimizeResponse: {
            /** Symbol */
            symbol: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Bars */
            bars: number;
            /** Metric */
            metric: string;
            /** Seed */
            seed: number | null;
            /** Initial Capital */
            initial_capital: number;
            /** Combinations Requested */
            combinations_requested: number;
            /** Combinations Evaluated */
            combinations_evaluated: number;
            /** Best Params */
            best_params: {
                [key: string]: unknown;
            };
            /** Best Metrics */
            best_metrics: {
                [key: string]: unknown;
            };
            /**
             * Results
             * @description Ranked best-first, truncated to top_n
             */
            results: {
                [key: string]: unknown;
            }[];
            /**
             * Skipped
             * @description Combinations the strategy itself rejected, e.g. short_window >= long_window. Reported rather than dropped.
             */
            skipped?: components["schemas"]["SkippedCombination"][];
            /** Caveat */
            caveat?: string | null;
        };
        /** StrategySchema */
        StrategySchema: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /**
             * Input Contract
             * @description 'single' takes one symbol's OHLCV frame; 'multi' takes a wide multi-symbol frame and cannot be backtested on a single symbol.
             * @enum {string}
             */
            input_contract: "single" | "multi";
            /** Params */
            params: components["schemas"]["ParamSchema"][];
            /**
             * Caveat
             * @description Set when the strategy is known to be unsound — surface it to the user.
             */
            caveat?: string | null;
        };
        /** TestListResponse */
        TestListResponse: {
            /** Count */
            count: number;
            /** Tests */
            tests: components["schemas"]["TestSchema"][];
        };
        /** TestSchema */
        TestSchema: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /**
             * Arity
             * @description 'single' takes one symbol, 'pair' exactly two, 'multi' two or more.
             * @enum {string}
             */
            arity: "single" | "pair" | "multi";
            /**
             * Input Kind
             * @description Whether the test consumes price levels or returns. The API performs the conversion — callers always send symbols.
             * @enum {string}
             */
            input_kind: "price" | "returns";
            /** Min Symbols */
            min_symbols: number;
            /** Params */
            params: components["schemas"]["ParamSchema"][];
            /** Caveat */
            caveat?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assets_api_v1_assets_get: {
        parameters: {
            query?: {
                /** @description Filter by 'equity' or 'crypto' */
                asset_class?: string | null;
                /** @description Case-insensitive symbol substring match */
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticker as stored, e.g. 'AAPL' or 'BTC-USD' */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            /** @description Symbol is not in the asset registry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ohlcv_api_v1_ohlcv__symbol__get: {
        parameters: {
            query: {
                /** @description Inclusive range start (ISO 8601) */
                start: string;
                /** @description Inclusive range end (ISO 8601) */
                end: string;
                /** @description Optional disambiguator. Omit it — symbols are unique in the current registry, and the API deliberately does not infer asset class from the ticker. */
                asset_class?: string | null;
                /** @description Filter by data provider */
                source?: string | null;
            };
            header?: never;
            path: {
                /** @description Ticker as stored, e.g. 'AAPL' or 'BTC-USD' */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OHLCVResponse"];
                };
            };
            /** @description Symbol is not in the asset registry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_v1_strategies_get: {
        parameters: {
            query?: {
                /** @description Filter by input contract. Pass 'single' for symbol-by-symbol backtests. */
                input_contract?: ("single" | "multi") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_v1_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registry id, e.g. 'ma_crossover' */
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySchema"];
                };
            };
            /** @description No such strategy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_screeners_api_v1_screeners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerListResponse"];
                };
            };
        };
    };
    get_screener_api_v1_screeners__screener_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registry id, e.g. 'low_volatility' */
                screener_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerSchema"];
                };
            };
            /** @description No such screener */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_screen_api_v1_screeners_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenResponse"];
                };
            };
            /** @description Unknown screener */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters, bad range, or too many symbols */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tests_api_v1_statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestListResponse"];
                };
            };
        };
    };
    get_test_api_v1_statistics__test_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registry id, e.g. 'adf' */
                test_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSchema"];
                };
            };
            /** @description No such test */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_test_api_v1_statistics__test_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registry id, e.g. 'johansen' */
                test_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatisticsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsResponse"];
                };
            };
            /** @description Unknown test or symbol */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wrong symbol count, invalid parameters, or no data */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_backtest_api_v1_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Unknown symbol or strategy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters, bad date range, or no data */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_portfolio_backtest_api_v1_backtest_portfolio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioBacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioBacktestResponse"];
                };
            };
            /** @description Unknown symbol or strategy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Single-asset strategy, bad weights, or no data */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    optimize_strategy_api_v1_optimize_strategy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyOptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOptimizeResponse"];
                };
            };
            /** @description Unknown symbol or strategy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad grid, metric, date range, or no valid combination */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    optimize_portfolio_api_v1_optimize_portfolio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioOptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOptimizeResponse"];
                };
            };
            /** @description Unknown symbol */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fewer than two symbols, or insufficient overlap */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_signals_api_v1_signals__symbol__get: {
        parameters: {
            query: {
                /** @description Registry id, e.g. 'ma_crossover' */
                strategy_id: string;
                /** @description Inclusive range start (ISO 8601) */
                start: string;
                /** @description Inclusive range end (ISO 8601) */
                end: string;
                /** @description JSON object of strategy parameters, e.g. {"short_window": 10, "long_window": 30}. Omitted parameters use registry defaults. Unknown names are rejected with 422 rather than ignored. */
                params?: string | null;
                /** @description Include the Close price alongside each signal */
                include_close?: boolean;
            };
            header?: never;
            path: {
                /** @description Ticker as stored, e.g. 'AAPL' */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsResponse"];
                };
            };
            /** @description Unknown symbol or strategy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid parameters, bad date range, or no data */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
