/**
 * api/ws.ts
 *
 * WebSocket backtest-progress protocol.
 *
 * IMPORTANT: these types are hand-written and are the ONLY part of the API
 * surface not generated by `npm run gen:api`. WebSocket routes never appear in
 * an OpenAPI document, so nothing checks them against the server. The authority
 * is the protocol docstring at the top of `api/routers/ws.py` — change one, change
 * the other.
 *
 * Phase 4 — React frontend
 */

import { API_BASE_URL } from './client'
import type { BacktestRequest } from './client'

export interface WsAccepted {
  type: 'accepted'
  symbol: string
  strategy_id: string
  strategy_name: string
}

export interface WsProgress {
  type: 'progress'
  stage: 'fetching' | 'running' | 'summarising'
  pct: number
  detail: string
}

export interface WsResult {
  type: 'result'
  symbol: string
  strategy_id: string
  strategy_name: string
  bars: number
  trades: number
  metrics: Record<string, number | null>
  caveat: string | null
  equity_curve?: Array<{ time: string; total: number }>
}

export interface WsError {
  type: 'error'
  detail: string
  code: number
}

export type WsMessage = WsAccepted | WsProgress | WsResult | WsError

/** http(s):// base URL -> ws(s):// endpoint. */
export function backtestSocketUrl(): string {
  const base = API_BASE_URL.replace(/^http/, 'ws')
  return `${base}/api/v1/ws/backtest`
}

/**
 * Run one backtest over a websocket, invoking `onMessage` for each server
 * message. Resolves with the final result, or rejects on error/early close.
 *
 * One backtest per connection — the server closes after `result` or `error`,
 * so callers reconnect for the next run.
 */
export function runBacktestOverSocket(
  request: BacktestRequest,
  onMessage: (message: WsMessage) => void,
): Promise<WsResult> {
  return new Promise((resolve, reject) => {
    const socket = new WebSocket(backtestSocketUrl())
    let settled = false

    socket.onopen = () => socket.send(JSON.stringify(request))

    socket.onmessage = (event) => {
      let message: WsMessage
      try {
        message = JSON.parse(event.data) as WsMessage
      } catch {
        return // ignore anything unparseable rather than killing the run
      }
      onMessage(message)

      if (message.type === 'result') {
        settled = true
        resolve(message)
        socket.close()
      } else if (message.type === 'error') {
        settled = true
        reject(new Error(message.detail))
        socket.close()
      }
    }

    socket.onerror = () => {
      if (!settled) {
        settled = true
        reject(new Error(`WebSocket error contacting ${backtestSocketUrl()}`))
      }
    }

    socket.onclose = () => {
      // A close before result/error means the run never completed — surface it
      // rather than leaving the promise pending forever.
      if (!settled) {
        settled = true
        reject(new Error('WebSocket closed before the backtest finished.'))
      }
    }
  })
}
