/**
 * api/ws.ts
 *
 * WebSocket backtest-progress protocol.
 *
 * IMPORTANT: these types are hand-written and are the ONLY part of the API
 * surface not generated by `npm run gen:api`. WebSocket routes never appear in
 * an OpenAPI document, so nothing checks them against the server. The authority
 * is the protocol docstring at the top of `api/routers/ws.py` — change one, change
 * the other.
 *
 * Phase 4 — React frontend
 */

import { API_BASE_URL } from './client'
import type { BacktestInput, SimulationInput, SimulationResponse } from './client'

export interface WsAccepted {
  type: 'accepted'
  symbol: string
  strategy_id: string
  strategy_name: string
}

export interface WsProgress {
  type: 'progress'
  stage: 'fetching' | 'running' | 'summarising'
  pct: number
  detail: string
  /** Present only on progress published from inside a worker (per path or per combination). */
  completed?: number
  total?: number
}

export interface WsResult {
  type: 'result'
  symbol: string
  strategy_id: string
  strategy_name: string
  bars: number
  /** A COUNT, not the log — unlike the REST response's `trades` array. */
  trades: number
  metrics: Record<string, number | null>
  caveat: string | null
  params: Record<string, number | string>
  seed: number | null
  initial_capital: number
  equity_curve?: Array<{ time: string; total: number }>
}

export interface WsError {
  type: 'error'
  detail: string
  code: number
}

export type WsMessage = WsAccepted | WsProgress | WsResult | WsError

/**
 * The simulation socket's result is the REST SimulationResponse verbatim
 * (the server dumps the same Pydantic model) plus the envelope's `type`.
 */
export type WsSimulationResult = SimulationResponse & { type: 'result' }
export type WsSimulationMessage = WsAccepted | WsProgress | WsSimulationResult | WsError

/** http(s):// base URL -> ws(s):// endpoint. */
export function backtestSocketUrl(): string {
  const base = API_BASE_URL.replace(/^http/, 'ws')
  return `${base}/api/v1/ws/backtest`
}

export function simulateSocketUrl(): string {
  const base = API_BASE_URL.replace(/^http/, 'ws')
  return `${base}/api/v1/ws/simulate`
}

/**
 * Run one request over a websocket, invoking `onMessage` for each server
 * message. Resolves with the final result, or rejects on error/early close.
 *
 * One run per connection — the server closes after `result` or `error`, so
 * callers reconnect for the next run. Every socket route speaks the same
 * accepted / progress / result / error envelope, so one runner serves all.
 */
function runOverSocket<TMessage extends { type: string }, TResult extends TMessage & { type: 'result' }>(
  url: string,
  what: string,
  request: unknown,
  onMessage: (message: TMessage) => void,
): Promise<TResult> {
  return new Promise((resolve, reject) => {
    const socket = new WebSocket(url)
    let settled = false

    socket.onopen = () => socket.send(JSON.stringify(request))

    socket.onmessage = (event) => {
      let message: TMessage
      try {
        message = JSON.parse(event.data) as TMessage
      } catch {
        return // ignore anything unparseable rather than killing the run
      }
      onMessage(message)

      if (message.type === 'result') {
        settled = true
        resolve(message as unknown as TResult)
        socket.close()
      } else if (message.type === 'error') {
        settled = true
        reject(new Error((message as unknown as WsError).detail))
        socket.close()
      }
    }

    socket.onerror = () => {
      if (!settled) {
        settled = true
        reject(new Error(`WebSocket error contacting ${url}`))
      }
    }

    socket.onclose = () => {
      // A close before result/error means the run never completed — surface it
      // rather than leaving the promise pending forever.
      if (!settled) {
        settled = true
        reject(new Error(`WebSocket closed before the ${what} finished.`))
      }
    }
  })
}

export function runBacktestOverSocket(
  request: BacktestInput,
  onMessage: (message: WsMessage) => void,
): Promise<WsResult> {
  return runOverSocket<WsMessage, WsResult>(backtestSocketUrl(), 'backtest', request, onMessage)
}

export function runSimulationOverSocket(
  request: SimulationInput,
  onMessage: (message: WsSimulationMessage) => void,
): Promise<WsSimulationResult> {
  return runOverSocket<WsSimulationMessage, WsSimulationResult>(
    simulateSocketUrl(),
    'simulation',
    request,
    onMessage,
  )
}
